# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create([
  {username: "admin", email: "admin@email.com", password: "1234567", bio: "This is an autogenerated admin user for demo purposes."},
  {username: "DemoUser", email: "demouser@email.com", password: "password", bio: "This is an autogenerated demo user for demo purposes."},
  {username: "ivo22", email: "ivo22@email.com", password: "123456", bio: "Just a city boy, born and raised in South Detroit!"},
  {username: "rmohr", email: "rmohr@email.com", password: "123456", bio: "Just a city girl, took the midnight train going anywhere!"},
  {username: "maxwolfwood", email: "iam@dog.com", password: "woofwoof8", bio: "Woof-woof, woofity-woof."},
  {username: "jbroden", email: "sega@atari.com", password: "nintendoSucks", bio: "Living just to find emotion."},
])